### ISSUE TITLE
Add user signup and login functionality

### ISSUE THREAD

**Issue by amiromayer** [LinkdropHQ/wallet-widget-monorepo#10]
# Description

# Subtasks included

- [x] Research key management and encryption options
- [x] Create utility functions for key management in SDK
- [x] Create utility functions for encryption in SDK
- [x] Add User mongoose model to Relay Service
- [ ] Add basic implementation of user signup and login endpoints to Relay Service
- [ ] Add validation middleware to controllers
- [ ] Add error handling

# Definition of done

# Reviewer
